export const CREATE_USER = 'CREAT_USER';
export const CREATE_USER_AUTH = 'CREAT_USER_AUTH';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USERS = 'UPDATE_USERS';
export const FETCH_MONEY = 'FETCH_MONEY';
export const WALLET_USER_REFILL = 'WALLET_USER_REFILL';
export const WALLETS_ALL = 'WALLETS_ALL';
export const TRANSACTIONS_ALL = 'TRANSACTIONS_ALL';
export const CRYPTO_ID = 'CRYPTO_ID';

